// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: internal/nginx/cache_repository/v1/cache_repository.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CacheRepository_List_FullMethodName = "/cache_repository_v1.CacheRepository/List"
)

// CacheRepositoryClient is the client API for CacheRepository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CacheRepositoryClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type cacheRepositoryClient struct {
	cc grpc.ClientConnInterface
}

func NewCacheRepositoryClient(cc grpc.ClientConnInterface) CacheRepositoryClient {
	return &cacheRepositoryClient{cc}
}

func (c *cacheRepositoryClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, CacheRepository_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheRepositoryServer is the server API for CacheRepository service.
// All implementations must embed UnimplementedCacheRepositoryServer
// for forward compatibility
type CacheRepositoryServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	mustEmbedUnimplementedCacheRepositoryServer()
}

// UnimplementedCacheRepositoryServer must be embedded to have forward compatible implementations.
type UnimplementedCacheRepositoryServer struct {
}

func (UnimplementedCacheRepositoryServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCacheRepositoryServer) mustEmbedUnimplementedCacheRepositoryServer() {}

// UnsafeCacheRepositoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CacheRepositoryServer will
// result in compilation errors.
type UnsafeCacheRepositoryServer interface {
	mustEmbedUnimplementedCacheRepositoryServer()
}

func RegisterCacheRepositoryServer(s grpc.ServiceRegistrar, srv CacheRepositoryServer) {
	s.RegisterService(&CacheRepository_ServiceDesc, srv)
}

func _CacheRepository_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheRepositoryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheRepository_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheRepositoryServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CacheRepository_ServiceDesc is the grpc.ServiceDesc for CacheRepository service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CacheRepository_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cache_repository_v1.CacheRepository",
	HandlerType: (*CacheRepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _CacheRepository_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/nginx/cache_repository/v1/cache_repository.proto",
}
